### ISSUE TITLE
How to generate a torus "properly" ?

### ISSUE THREAD

**Issue by tubiana** [weria-pezeshkian/TS2CG1.2#1]
Hi :-) 

I would like to generate a torus, like on this screenshot (generated with BUMPY, but with this system since the lipids are not homogeneously distributed, it makes holes and the torus became smaller during the MD).
![Umol_2](https://user-images.githubusercontent.com/8037224/218491238-9ef44144-7418-4fd9-869a-bf5ae051cabd.png)

So I have generated a torus in Blender (add > Torus > then I subdived) , used the script to convert it into STI format, but when I use the command `PLM -TSfile newTS.tsi -bilayerThickness 3.8 -rescalefactor 10 10 10` I have some error that provide me to use the `PCG` command then.
Output in log file but roughfly here's the errors : 
```
 Warning : This system does not look like a closed system or the triangles orination are not consistent 
 WARNING: vertex has a zero area 

 WARNING: normal has zero size 

-nan  -nan  -nan  error: delta is negative, this means curvature cannot be found 
0

```
[out.log](https://github.com/weria-pezeshkian/TS2CG1.2/files/10723376/out.log)
[torus_V1.stl.zip](https://github.com/weria-pezeshkian/TS2CG1.2/files/10723393/torus_V1.stl.zip)

Is there a "clean way" to generate a mesh in blender ? 

Thank you for your help =D

**Comment by weria-pezeshkian** [comment]
Hi,

Could you send mew the newTS.tsi file?

Below is a tsi file for a torus but maybe you need something more generic.

[torus.tsi.zip](https://github.com/weria-pezeshkian/TS2CG1.2/files/10723824/torus.tsi.zip)

Best,

**Comment by tubiana** [comment]
[newTS.tsi.zip](https://github.com/weria-pezeshkian/TS2CG1.2/files/10724729/newTS.tsi.zip)
Thank you for your quick answer ! Of course! Here's my tsi file! 
I check yours, and it seems that yours have something bellow  "inclusions" line. (mine is at set at 0).

I will start to play with your tsi (thank you so much =D!), but in the futur I have to generate different radius and shape so maybe I have to find out how to do it myself...

Best!
Thibault.

**Comment by weria-pezeshkian** [comment]
Dear Thibault,

Having "inclusions 0" is just fine. As a matter of fact you may remove all the inclusion section from my file. 

Your file does not contains enough triangles. The number of the vertices and triangles are equal. That cannot be the case.  For a torus number of triangles is twice the number of the vertices.  

Best regards,
WP

**Comment by tubiana** [comment]
Ok great thank you!! I will work on that ;) 

Best regards,
Thibault.

**Comment by tubiana** [comment]
Edit : It works! Thank you :) 
On blender I just added a triangulate modifier + apply before explorting my mesh.
![Umol_3](https://user-images.githubusercontent.com/8037224/218572468-8605ebeb-613c-4f0b-ab2e-defdd5129851.png)
