### ISSUE TITLE
multiple protein placement

### ISSUE THREAD

**Issue by TommyBiomodelling** [weria-pezeshkian/TS2CG1.2#17]
hello
I am trying to insert multiple proteins into a vesicle, but I get a strange error from the point folder saying that I am missing " error: file with file name ./point/OuterBM.dat does not exist" I find this very strange, how do I make this file and why is it not generated when i use TS2CG? 
Best wishes,
Tommy

**Comment by fabianschuhmann** [comment]
Hi Tommy,
please let me know what branch you are on, as the protein placement is being enhanced at the moment and is in a quite buggy state still.

The error could already come beforehand though. The point folder needs to exist. You could, for instance, create the point folder by running TS2CG PLM.

**Comment by TommyBiomodelling** [comment]
I am currently constructing a workflow with FreeDTS to get the tsi file needed to make inclusions. The tsi+inclusions file I give to TS2CG PLM and then TS2CG PCG to coarse grain it. If by branch you mean version, I am using TS2CG version 1.2.2.
I have two folders named "point" and "pointvisualization_data" but remain empty

**Comment by fabianschuhmann** [comment]
Hi Tommy,
the point folder should be populated through PLM alone. Can you provide the terminal output of PLM, so we can check what is going on?

**Comment by TommyBiomodelling** [comment]
Turns out I was just being stupid as i mistook the inclusion id for triangles instead of the vertices. It works now :)
