### ISSUE TITLE
Leaflet decisions in interacting bilayers.

### ISSUE THREAD

**Issue by MishterBluesky** [weria-pezeshkian/TS2CG1.2#2]
Dear Weria,

I thought to copy this issue here as well. Thank you for advising to use v1.2, it does allow free floating membranes, or at least the version 1 month ago did at the time, it may now be non functional in this regard.

In vesicles, outer is always outer and inner is always inner. However in a system with two bilayers these can switch eg below

<img width="752" alt="image" src="https://github.com/weria-pezeshkian/TS2CG1.2/assets/19994410/65ef6a6e-fabf-436e-b175-7dbbd696b5d3">

I am getting issues, with a correctly formed .tsi which i can attach if you would like at the PLM step. The issue being that there is a crossover event that shouldnt occur, switching upper and lower leaflets where they shouldnt switch.

How can this issue be resolved do you think?

BW

Chris

**Comment by MishterBluesky** [comment]
The TSI provided is a one layer matrix with a pore that connects two membranes layers, similar to above but just green or blue, without the undulation caused by the crossover event

**Comment by MishterBluesky** [comment]
here is .tsi if youd like to try yourself. Im also using an older (one or two month old) version of ts2cg which still enabled freefloating membranes at the time.
[3_Tunnel20NMDEPTH.txt](https://github.com/weria-pezeshkian/TS2CG1.2/files/12672526/3_Tunnel20NMDEPTH.txt)

**Comment by MishterBluesky** [comment]
If youd like we could have a call or email discussion about above if interests you as I imagine this could be a time sink if there is no immediate solution.

**Comment by weria-pezeshkian** [comment]
Dear Chris, 

I think the reason for this is because the orientation of your triangles are not consistent (all must be clockwise or anti clockwise). In the neck and on surfaces they have different orientation and therefore the normal vector changes orientation (pointing upward or downward) which lead to this mixing of the leaflet. So still problems with your tsi file.

**Comment by weria-pezeshkian** [comment]
One example: for a triangle represented by three vertices 1 2 3, orientation of 2 3 1, 3 1 2 are all the same. But 1 3 2 will be different.

**Comment by weria-pezeshkian** [comment]
Dear Chris,

I do not know what is your exact question. Do you mean why the triangles should be in correct orientation? If yes, then please check how "half-edge" algorithm works.

Best regards,

**Comment by MishterBluesky** [comment]
Thanks
